services:
  db:
    image: postgres:16
    container_name: flowapp_learn_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: flowapp_learn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d flowapp_learn"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: ./app
    container_name: flowapp_learn_app
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: flowapp_learn
      DB_USER: lernuser
      DB_PASSWORD: lernuser
      DB_ADMIN_USER: postgres
      DB_ADMIN_PASSWORD: postgres
      SQL_INIT_PATH: /app/db/01_schema_and_data.sql
      FLASK_DEBUG: "1"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - ./db/init/01_schema_and_data.sql:/app/db/01_schema_and_data.sql:ro
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
