"""Beginner SQL academy: interactive steps, not documentation pages."""

ORDERS = [
    {"id": 1, "order_number": 4711, "client": "Red Bull", "status": "open", "quantity": 12, "created_at": "2026-09-08"},
    {"id": 2, "order_number": 4712, "client": "ETE", "status": "finished", "quantity": 4, "created_at": "2026-09-07"},
    {"id": 3, "order_number": 4713, "client": "Red Bull", "status": "open", "quantity": 25, "created_at": "2026-09-09"},
    {"id": 4, "order_number": 4714, "client": "ETE", "status": "open", "quantity": 8, "created_at": "2026-09-06"},
    {"id": 5, "order_number": 4715, "client": "Red Bull", "status": "finished", "quantity": 30, "created_at": "2026-09-05"},
    {"id": 6, "order_number": 4716, "client": "Nordlog", "status": "open", "quantity": 15, "created_at": "2026-09-10"},
    {"id": 7, "order_number": 4717, "client": "ETE", "status": "cancelled", "quantity": 2, "created_at": "2026-09-04"},
    {"id": 8, "order_number": 4718, "client": "Red Bull", "status": "open", "quantity": 50, "created_at": "2026-09-10"},
]

STOCK = [
    {"id": 1, "item": "Palette A", "quantity": 40, "weight": 120},
    {"id": 2, "item": "Palette B", "quantity": 8, "weight": 80},
    {"id": 3, "item": "Karton C", "quantity": 15, "weight": 25},
    {"id": 4, "item": "Palette D", "quantity": 3, "weight": 100},
]

CLIENTS = [
    {"id": 10, "name": "Red Bull", "country": "AT"},
    {"id": 20, "name": "ETE", "country": "DE"},
    {"id": 30, "name": "Nordlog", "country": "CH"},
]

CONCEPTS = [
    {"id": "TABLE", "label": "Tabellen"},
    {"id": "SELECT", "label": "SELECT"},
    {"id": "FROM", "label": "FROM"},
    {"id": "WHERE", "label": "WHERE"},
    {"id": "COMPARE", "label": "Vergleiche"},
    {"id": "AND", "label": "AND / OR"},
    {"id": "ORDER BY", "label": "ORDER BY"},
    {"id": "LIMIT", "label": "LIMIT"},
]


def table(name, label, rows, columns=None):
    columns = columns or list(rows[0].keys())
    return {
        "name": name,
        "label": label,
        "columns": columns,
        "rows": [{k: r[k] for k in columns} for r in rows],
    }


def orders_table(*columns):
    cols = list(columns) if columns else ["id", "order_number", "client", "status"]
    return table("orders", "Aufträge", ORDERS, cols)


def stock_table(*columns):
    cols = list(columns) if columns else ["id", "item", "quantity", "weight"]
    return table("stock", "Bestand", STOCK, cols)


HINT_WHERE = [
    "Du möchtest Datensätze filtern. Welche SQL-Anweisung ist dafür zuständig?",
    "SELECT * FROM orders _____ status = 'open';",
    "SELECT * FROM orders WHERE ______ = 'open';",
]


ACADEMY = {
    "id": "sql",
    "label": "SQL Grundlagen",
    "blurb": "Vom ersten Blick in eine Tabelle bis zur eigenen Abfrage.",
    "concepts": CONCEPTS,
    "lessons": [
        {
            "id": "ch0",
            "chapter": 0,
            "title": "Daten verstehen",
            "minutes": 6,
            "goal": "Du erkennst Zeilen, Spalten, Werte und IDs — noch ohne SQL zu schreiben.",
            "concepts": ["TABLE"],
            "model": ["TABLE"],
            "steps": [
                {
                    "type": "look",
                    "title": "Eine Tabelle voller Aufträge",
                    "text": "Das hier ist eine **Tabelle**. Stell sie dir wie eine Excel-Liste vor: oben die Überschriften, darunter die Einträge.",
                    "table": orders_table(),
                    "note": "Jede Zeile ist ein Auftrag. Jede Spalte ist eine Art von Information.",
                    "cta": "Ich habe die Tabelle angesehen",
                },
                {
                    "type": "inspect",
                    "title": "Welche Spalte enthält den Kunden?",
                    "text": "Tippe auf die **Spaltenüberschrift**, in der der Kundenname steht.",
                    "table": orders_table(),
                    "interaction": "click_column",
                    "answer": "client",
                    "concepts": ["TABLE"],
                    "feedback_ok": "Genau. Die Spalte `client` speichert, zu wem der Auftrag gehört.",
                    "feedback_bad": "Schau, in welcher Spalte Namen wie Red Bull und ETE stehen.",
                },
                {
                    "type": "inspect",
                    "title": "Wie viele Datensätze sind das?",
                    "text": "Ein Datensatz ist eine **Zeile**. Wie viele Aufträge liegen in der Tabelle?",
                    "table": orders_table(),
                    "interaction": "number",
                    "answer": 8,
                    "concepts": ["TABLE"],
                    "feedback_ok": "Richtig — 8 Zeilen, also 8 Aufträge.",
                    "feedback_bad": "Zähle die Zeilen unter der Überschrift. Jede Zeile ist ein Auftrag.",
                },
                {
                    "type": "inspect",
                    "title": "Welchen Status hat Auftrag 4712?",
                    "text": "Finde die Zeile mit Auftragsnummer **4712** und tippe auf den Status-Wert.",
                    "table": orders_table(),
                    "interaction": "click_cell",
                    "answer": {"column": "status", "value": "finished"},
                    "concepts": ["TABLE"],
                    "feedback_ok": "Auftrag 4712 ist `finished` — abgeschlossen.",
                    "feedback_bad": "Gehe in der Spalte `order_number` zu 4712, dann nach rechts zur Spalte `status`.",
                },
                {
                    "type": "inspect",
                    "title": "Markiere den kompletten Auftrag 4713",
                    "text": "Eine **Zeile** gehört immer zusammen. Tippe irgendwo in die Zeile von Auftrag **4713**.",
                    "table": orders_table(),
                    "interaction": "click_row",
                    "id_field": "order_number",
                    "answer": 4713,
                    "concepts": ["TABLE"],
                    "feedback_ok": "Das ist ein Datensatz: id 3, Nummer 4713, Kunde Red Bull, Status open.",
                    "feedback_bad": "Suche die Zeile, in der `order_number` 4713 ist, und klicke sie an.",
                },
                {
                    "type": "mcq",
                    "title": "Wozu ist die Spalte id da?",
                    "text": "Links steht in jeder Zeile eine `id`.",
                    "question": "Was bedeutet die id?",
                    "options": [
                        {"text": "Eine eindeutige Nummer für genau diesen Datensatz.", "correct": True},
                        {"text": "Die Anzahl der Aufträge in der Tabelle.", "correct": False},
                        {"text": "Der Name des Kunden.", "correct": False},
                    ],
                    "concepts": ["TABLE"],
                    "explain": "Die id identifiziert eine Zeile. Zwei Aufträge können denselben Kunden haben — aber nie dieselbe id.",
                },
                {
                    "type": "look",
                    "title": "Genau solche Fragen stellen wir gleich SQL",
                    "text": "Du hast gerade von Hand gesucht: Welche Spalte? Welche Zeile? Welcher Wert?\n\nEine Datenbank kann dieselben Fragen beantworten — mit einer kurzen Anweisung namens **SQL**.\n\nAls Nächstes siehst du die erste Abfrage. Du musst sie noch nicht schreiben.",
                    "table": orders_table(),
                    "cta": "Weiter zur ersten Abfrage",
                },
            ],
        },
        {
            "id": "ch1",
            "chapter": 1,
            "title": "Die erste SQL-Abfrage",
            "minutes": 8,
            "goal": "Du verstehst `SELECT * FROM orders` und führst deine erste Abfrage aus.",
            "concepts": ["SELECT", "FROM"],
            "model": ["SELECT", "FROM"],
            "steps": [
                {
                    "type": "explain",
                    "title": "SQL ist eine Frage an die Tabelle",
                    "text": "Klicke die beiden Teile an. Jeder Teil beantwortet eine Frage.",
                    "sql": "SELECT *\nFROM orders;",
                    "plain": "Zeige mir alle Informationen aus den Aufträgen.",
                    "parts": [
                        {
                            "match": "SELECT *",
                            "token": "SELECT",
                            "question": "Was möchte ich sehen?",
                            "answer": "Alle Spalten. Der Stern `*` bedeutet „alles“.",
                        },
                        {
                            "match": "FROM orders",
                            "token": "FROM",
                            "question": "Woher kommen die Daten?",
                            "answer": "Aus der Tabelle `orders` — unseren Aufträgen.",
                        },
                    ],
                    "concepts": ["SELECT", "FROM"],
                },
                {
                    "type": "demo",
                    "title": "Ausführen und vergleichen",
                    "text": "Links die Tabelle **vorher**. Führe die Query aus — rechts siehst du, was SQL zurückgibt. Bei `SELECT *` sind das dieselben Zeilen.",
                    "sql": "SELECT * FROM orders;",
                    "table": orders_table("id", "order_number", "client", "status"),
                    "visualize": "all",
                    "concepts": ["SELECT", "FROM"],
                },
                {
                    "type": "predict",
                    "title": "Welche Zeilen kommen zurück?",
                    "text": "Diese Query holt alle Spalten, ohne zu filtern. Markiere die Zeilen, die im Ergebnis erscheinen.",
                    "sql": "SELECT * FROM orders;",
                    "table": orders_table(),
                    "expected_ids": [1, 2, 3, 4, 5, 6, 7, 8],
                    "id_field": "id",
                    "execute": True,
                    "concepts": ["SELECT", "FROM"],
                    "feedback_ok": "Richtig: ohne WHERE kommen alle 8 Aufträge zurück.",
                    "feedback_bad": "`SELECT *` ohne `WHERE` bedeutet: alle Zeilen, alle Spalten.",
                },
                {
                    "type": "explain",
                    "title": "Nicht immer alle Spalten",
                    "text": "Oft brauchst du nur eine Information. Dann nennst du die Spalte statt `*`.",
                    "sql": "SELECT order_number\nFROM orders;",
                    "plain": "Zeige mir nur die Auftragsnummern aus den Aufträgen.",
                    "before_table": orders_table("id", "order_number", "client", "status"),
                    "after_table": table("orders", "Ergebnis", ORDERS, ["order_number"]),
                    "parts": [
                        {
                            "match": "SELECT order_number",
                            "token": "SELECT",
                            "question": "Was möchte ich sehen?",
                            "answer": "Nur die Spalte `order_number` — id, Kunde und Status fallen weg.",
                        },
                        {
                            "match": "FROM orders",
                            "token": "FROM",
                            "question": "Woher?",
                            "answer": "Immer noch aus `orders`. FROM ändert sich nicht, nur SELECT.",
                        },
                    ],
                    "concepts": ["SELECT"],
                },
                {
                    "type": "build",
                    "title": "Baue die erste Query",
                    "prompt": "Zeige alle Spalten aller Aufträge.",
                    "pieces": ["SELECT", "*", "FROM", "orders"],
                    "distractors": ["WHERE", "clients"],
                    "solution": "SELECT * FROM orders;",
                    "concepts": ["SELECT", "FROM"],
                    "hints": [
                        "Zuerst: Was willst du sehen? Dann: Woher kommen die Daten?",
                        "SELECT * FROM ______;",
                        "SELECT * FROM orders;",
                    ],
                },
                {
                    "type": "write",
                    "title": "Jetzt selbst schreiben",
                    "prompt": "Zeige alle Informationen aus der Tabelle orders.",
                    "starter": "",
                    "placeholder": "SELECT …",
                    "solution": "SELECT * FROM orders;",
                    "concepts": ["SELECT", "FROM"],
                    "hints": [
                        "Zwei Teile: SELECT sagt was, FROM sagt woher.",
                        "SELECT * FROM ______;",
                    ],
                },
            ],
        },
        {
            "id": "ch2",
            "chapter": 2,
            "title": "SELECT verstehen",
            "minutes": 8,
            "goal": "SELECT bestimmt, welche Informationen im Ergebnis erscheinen — nicht, welche Zeilen.",
            "concepts": ["SELECT"],
            "model": ["SELECT", "FROM"],
            "steps": [
                {
                    "type": "look",
                    "title": "SELECT wählt Spalten",
                    "text": "`WHERE` (kommt gleich) filtert **Zeilen**. `SELECT` wählt **Spalten**.\n\nStell dir vor, du blendest in Excel Spalten aus — die Zeilen bleiben.",
                    "table": orders_table("order_number", "status"),
                    "note": "Nur Nummer und Status — id und Kunde sind weg, aber alle 8 Aufträge sind noch da.",
                    "cta": "Weiter",
                },
                {
                    "type": "predict-cols",
                    "title": "Welche Spalten erscheinen?",
                    "text": "Markiere die Spalten, die diese Query im Ergebnis hat.",
                    "sql": "SELECT order_number, status\nFROM orders;",
                    "table": orders_table(),
                    "expected_columns": ["order_number", "status"],
                    "concepts": ["SELECT"],
                    "feedback_ok": "Ja: nur `order_number` und `status`. Die Zeilen bleiben alle.",
                    "feedback_bad": "Nach SELECT stehen genau die Spalten, die du sehen willst.",
                },
                {
                    "type": "demo",
                    "title": "Query ausführen",
                    "text": "Sieh zu, wie aus vier Spalten zwei werden.",
                    "sql": "SELECT order_number, status FROM orders;",
                    "table": orders_table(),
                    "visualize": "columns",
                    "keep_columns": ["order_number", "status"],
                    "concepts": ["SELECT"],
                },
                {
                    "type": "build",
                    "title": "Nur Nummer und Status",
                    "prompt": "Zeige Auftragsnummer und Status aller Aufträge.",
                    "pieces": ["SELECT", "order_number", ",", "status", "FROM", "orders"],
                    "distractors": ["*", "client", "WHERE"],
                    "solution": "SELECT order_number, status FROM orders;",
                    "strict_columns": True,
                    "concepts": ["SELECT"],
                    "hints": [
                        "SELECT bestimmt die Spalten. Mehrere Spalten trennst du mit Komma.",
                        "SELECT order_number, ______ FROM orders;",
                    ],
                },
                {
                    "type": "fill",
                    "title": "Spalten ergänzen",
                    "prompt": "Zeige nur die Auftragsnummer.",
                    "template": "SELECT ___\nFROM orders;",
                    "solution": "SELECT order_number FROM orders;",
                    "strict_columns": True,
                    "concepts": ["SELECT"],
                    "hints": [
                        "Welche Spalte enthält die Auftragsnummer?",
                        "SELECT order_number FROM orders;",
                    ],
                },
                {
                    "type": "write",
                    "title": "Selbst wählen",
                    "prompt": "Zeige zu jedem Auftrag den Kunden und den Status.",
                    "placeholder": "SELECT …",
                    "solution": "SELECT client, status FROM orders;",
                    "strict_columns": True,
                    "concepts": ["SELECT"],
                    "hints": [
                        "Zwei Spalten, getrennt durch Komma. Kein WHERE nötig.",
                        "SELECT client, status FROM orders;",
                    ],
                },
                {
                    "type": "mcq",
                    "title": "Kurz checken",
                    "question": "Was bestimmt SELECT?",
                    "options": [
                        {"text": "Welche Informationen (Spalten) im Ergebnis erscheinen.", "correct": True},
                        {"text": "Welche Zeilen gelöscht werden.", "correct": False},
                        {"text": "Wie die Tabelle heißt.", "correct": False},
                    ],
                    "concepts": ["SELECT"],
                    "explain": "FROM sagt woher, SELECT sagt was. Zeilen filtert später WHERE.",
                },
            ],
        },
        {
            "id": "ch3",
            "chapter": 3,
            "title": "WHERE",
            "minutes": 10,
            "goal": "WHERE entscheidet, welche Zeilen berücksichtigt werden.",
            "concepts": ["WHERE"],
            "model": ["SELECT", "FROM", "WHERE"],
            "steps": [
                {
                    "type": "explain",
                    "title": "Nicht alle Zeilen sind interessant",
                    "text": "Im Lager willst du oft nur die **offenen** Aufträge. Dafür kommt ein dritter Satzteil dazu.",
                    "sql": "SELECT *\nFROM orders\nWHERE status = 'open';",
                    "plain": "Zeige alle Spalten der Aufträge, aber nur die mit Status open.",
                    "parts": [
                        {"match": "SELECT *", "token": "SELECT", "question": "Was?", "answer": "Alle Spalten."},
                        {"match": "FROM orders", "token": "FROM", "question": "Woher?", "answer": "Aus den Aufträgen."},
                        {
                            "match": "WHERE status = 'open'",
                            "token": "WHERE",
                            "question": "Welche?",
                            "answer": "Nur Zeilen, bei denen status genau `open` ist. Textwerte stehen in einfachen Anführungszeichen.",
                        },
                    ],
                    "concepts": ["WHERE"],
                },
                {
                    "type": "demo",
                    "title": "Die anderen Zeilen fallen weg",
                    "text": "Führe aus. Nicht passende Zeilen werden ausgegraut — SQL liefert sie nicht mit.",
                    "sql": "SELECT * FROM orders WHERE status = 'open';",
                    "table": orders_table(),
                    "visualize": "where",
                    "match_column": "status",
                    "match_value": "open",
                    "concepts": ["WHERE"],
                },
                {
                    "type": "predict",
                    "title": "Welche Datensätze kommen zurück?",
                    "text": "Markiere die Zeilen, die diese Abfrage liefert.",
                    "sql": "SELECT * FROM orders WHERE status = 'open';",
                    "table": orders_table(),
                    "expected_ids": [1, 3, 4, 6, 8],
                    "id_field": "id",
                    "execute": True,
                    "visualize": "where",
                    "concepts": ["WHERE"],
                    "feedback_ok": "Offen sind 4711, 4713, 4714, 4716 und 4718. Die anderen haben einen anderen Status.",
                    "feedback_bad": "Schau in die Spalte `status`. Nur `open` zählt — `finished` und `cancelled` nicht.",
                },
                {
                    "type": "build",
                    "title": "Filter bauen",
                    "prompt": "Zeige alle offenen Aufträge.",
                    "pieces": ["SELECT", "*", "FROM", "orders", "WHERE", "status", "=", "'open'"],
                    "distractors": ["'finished'", "ORDER", "BY"],
                    "solution": "SELECT * FROM orders WHERE status = 'open';",
                    "concepts": ["WHERE"],
                    "hints": HINT_WHERE,
                },
                {
                    "type": "fill",
                    "title": "Nur den Filter ergänzen",
                    "prompt": "Zeige alle offenen Aufträge.",
                    "template": "SELECT *\nFROM orders\nWHERE ___;",
                    "solution": "SELECT * FROM orders WHERE status = 'open';",
                    "concepts": ["WHERE"],
                    "hints": [
                        "Die Spalte heißt status, der gesuchte Wert open.",
                        "WHERE status = 'open'",
                    ],
                },
                {
                    "type": "write",
                    "title": "Selbst filtern",
                    "prompt": "Zeige alle abgeschlossenen Aufträge (Status finished).",
                    "placeholder": "SELECT …",
                    "solution": "SELECT * FROM orders WHERE status = 'finished';",
                    "concepts": ["WHERE"],
                    "hints": [
                        "Dieselbe Struktur wie eben, nur ein anderer Status-Wert.",
                        "SELECT * FROM orders WHERE status = 'finished';",
                    ],
                },
                {
                    "type": "apply",
                    "title": "Ohne den Befehl zu verraten",
                    "prompt": "Im Lager liegen viele Aufträge. Finde alle Aufträge von ETE.",
                    "placeholder": "SELECT …",
                    "solution": "SELECT * FROM orders WHERE client = 'ETE';",
                    "concepts": ["WHERE"],
                    "hints": [
                        "Du suchst nicht alle Zeilen — nur die eines Kunden.",
                        "Die Kundenspalte heißt client.",
                        "SELECT * FROM orders WHERE client = 'ETE';",
                    ],
                },
            ],
        },
        {
            "id": "ch4",
            "chapter": 4,
            "title": "Vergleiche",
            "minutes": 8,
            "goal": "Du siehst sofort, welche Zeilen =, !=, > und >= erfüllen.",
            "concepts": ["COMPARE", "WHERE"],
            "model": ["SELECT", "FROM", "WHERE"],
            "steps": [
                {
                    "type": "look",
                    "title": "Vergleich ist eine Ja/Nein-Frage pro Zeile",
                    "text": "SQL prüft jede Zeile: Ist die Bedingung wahr?\n\n`=` gleich · `!=` ungleich · `>` größer · `<` kleiner · `>=` mindestens · `<=` höchstens",
                    "table": orders_table("order_number", "client", "quantity"),
                    "note": "quantity ist die bestellte Menge. Damit kannst du „mehr als 10 Stück“ fragen.",
                    "cta": "Zeilen markieren",
                },
                {
                    "type": "predict",
                    "title": "quantity > 10",
                    "text": "Markiere jede Zeile, für die `quantity > 10` wahr ist.",
                    "sql": "SELECT * FROM orders WHERE quantity > 10;",
                    "table": orders_table("id", "order_number", "client", "quantity"),
                    "expected_ids": [1, 3, 5, 6, 8],
                    "id_field": "id",
                    "execute": True,
                    "concepts": ["COMPARE"],
                    "feedback_ok": "12, 25, 30, 15 und 50 sind größer als 10. 4, 8 und 2 nicht.",
                    "feedback_bad": "`>` bedeutet echt größer. 10 selbst würde nicht zählen — hier liegt keine 10.",
                },
                {
                    "type": "predict",
                    "title": "Nicht abgeschlossen",
                    "text": "Markiere die Zeilen für `status != 'finished'`.",
                    "sql": "SELECT * FROM orders WHERE status != 'finished';",
                    "table": orders_table(),
                    "expected_ids": [1, 3, 4, 6, 7, 8],
                    "id_field": "id",
                    "execute": True,
                    "concepts": ["COMPARE"],
                    "feedback_ok": "`!=` schließt nur `finished` aus. Offen und storniert bleiben.",
                    "feedback_bad": "Ungleich `finished` sind open **und** cancelled.",
                },
                {
                    "type": "predict",
                    "title": "Schwere Paletten",
                    "text": "Im Bestand: welche Zeilen erfüllen `weight >= 100`?",
                    "sql": "SELECT * FROM stock WHERE weight >= 100;",
                    "table": stock_table(),
                    "expected_ids": [1, 4],
                    "id_field": "id",
                    "execute": True,
                    "concepts": ["COMPARE"],
                    "feedback_ok": "`>=` nimmt 100 mit. Palette A (120) und Palette D (100). 80 und 25 fallen weg.",
                    "feedback_bad": "`>=` bedeutet mindestens 100 — die 100 zählt mit.",
                },
                {
                    "type": "build",
                    "title": "Große Mengen",
                    "prompt": "Zeige Aufträge mit einer Menge von mehr als 10.",
                    "pieces": ["SELECT", "*", "FROM", "orders", "WHERE", "quantity", ">", "10"],
                    "distractors": ["=", "<", "100"],
                    "solution": "SELECT * FROM orders WHERE quantity > 10;",
                    "concepts": ["COMPARE", "WHERE"],
                    "hints": [
                        "Du vergleichst eine Zahl. Welches Zeichen bedeutet „größer als“?",
                        "WHERE quantity > 10",
                    ],
                },
                {
                    "type": "write",
                    "title": "Mindestgewicht",
                    "prompt": "Zeige alle Bestandszeilen mit einem Gewicht von mindestens 100.",
                    "placeholder": "SELECT …",
                    "solution": "SELECT * FROM stock WHERE weight >= 100;",
                    "concepts": ["COMPARE"],
                    "hints": [
                        "Die Tabelle heißt stock, die Spalte weight.",
                        "SELECT * FROM stock WHERE weight >= 100;",
                    ],
                },
            ],
        },
        {
            "id": "ch5",
            "chapter": 5,
            "title": "AND / OR / NOT",
            "minutes": 12,
            "goal": "Du trennst bewusst: beide Bedingungen (AND) oder mindestens eine (OR).",
            "concepts": ["AND"],
            "model": ["SELECT", "FROM", "WHERE"],
            "steps": [
                {
                    "type": "look",
                    "title": "Zwei Bedingungen, ein Unterschied",
                    "text": "**AND** — beide Bedingungen müssen stimmen.\n\n**OR** — mindestens eine muss stimmen.\n\n**NOT** — die Bedingung soll gerade nicht stimmen.",
                    "table": orders_table("order_number", "client", "status"),
                    "note": "Red Bull hat offene und abgeschlossene Aufträge. ETE ebenfalls.",
                    "cta": "AND ausprobieren",
                },
                {
                    "type": "predict",
                    "title": "AND: beide müssen stimmen",
                    "text": "Markiere Zeilen, die **Red Bull und offen** sind.",
                    "sql": "SELECT * FROM orders WHERE client = 'Red Bull' AND status = 'open';",
                    "table": orders_table(),
                    "expected_ids": [1, 3, 8],
                    "id_field": "id",
                    "execute": True,
                    "concepts": ["AND"],
                    "feedback_ok": "4711, 4713, 4718. 4715 ist Red Bull, aber finished — AND lässt sie weg.",
                    "feedback_bad": "Red Bull allein reicht nicht. Status muss zusätzlich open sein.",
                },
                {
                    "type": "predict",
                    "title": "OR: eine reicht",
                    "text": "Markiere Zeilen, die **Red Bull oder offen** sind (mindestens eins von beiden).",
                    "sql": "SELECT * FROM orders WHERE client = 'Red Bull' OR status = 'open';",
                    "table": orders_table(),
                    "expected_ids": [1, 3, 4, 5, 6, 8],
                    "id_field": "id",
                    "execute": True,
                    "concepts": ["AND"],
                    "feedback_ok": "Jetzt ist auch 4715 (Red Bull, finished) dabei — OR braucht nur eine Seite. ETE-finished und cancelled fehlen.",
                    "feedback_bad": "OR ist größer als AND: jeder Red-Bull-Auftrag **und** jeder offene Auftrag.",
                },
                {
                    "type": "build",
                    "title": "Beide Bedingungen",
                    "prompt": "Zeige alle offenen Red-Bull-Aufträge.",
                    "pieces": ["SELECT", "*", "FROM", "orders", "WHERE", "client", "=", "'Red Bull'", "AND", "status", "=", "'open'"],
                    "distractors": ["OR"],
                    "solution": "SELECT * FROM orders WHERE client = 'Red Bull' AND status = 'open';",
                    "concepts": ["AND", "WHERE"],
                    "hints": [
                        "Kunde und Status müssen gleichzeitig passen. AND oder OR?",
                        "WHERE client = 'Red Bull' AND status = 'open'",
                    ],
                },
                {
                    "type": "write",
                    "title": "Mindestens eine",
                    "prompt": "Zeige Aufträge, die storniert **oder** abgeschlossen sind.",
                    "placeholder": "SELECT …",
                    "solution": "SELECT * FROM orders WHERE status = 'cancelled' OR status = 'finished';",
                    "concepts": ["AND"],
                    "hints": [
                        "Zwei Status-Werte, es reicht wenn einer stimmt.",
                        "WHERE status = 'cancelled' OR status = 'finished'",
                    ],
                },
                {
                    "type": "apply",
                    "title": "AND und OR nicht verwechseln",
                    "prompt": "Finde offene Aufträge von ETE. Nur die, die wirklich beides erfüllen.",
                    "placeholder": "SELECT …",
                    "solution": "SELECT * FROM orders WHERE client = 'ETE' AND status = 'open';",
                    "concepts": ["AND"],
                    "hints": [
                        "Wenn du OR nimmst, kommen auch ETE-Aufträge mit anderem Status.",
                        "SELECT * FROM orders WHERE client = 'ETE' AND status = 'open';",
                    ],
                },
                {
                    "type": "mcq",
                    "title": "NOT",
                    "question": "Was liefert `WHERE NOT status = 'open'`?",
                    "options": [
                        {"text": "Alle Zeilen, deren Status nicht open ist.", "correct": True},
                        {"text": "Nur die offenen Zeilen.", "correct": False},
                        {"text": "Gar keine Zeilen.", "correct": False},
                    ],
                    "concepts": ["AND"],
                    "explain": "`NOT` dreht die Bedingung um. Dasselbe Ziel erreichst du oft mit `status != 'open'`.",
                },
            ],
        },
        {
            "id": "ch6",
            "chapter": 6,
            "title": "ORDER BY und LIMIT",
            "minutes": 8,
            "goal": "Du sortierst Ergebnisse und begrenzst, wie viele Zeilen du siehst.",
            "concepts": ["ORDER BY", "LIMIT"],
            "model": ["SELECT", "FROM", "WHERE", "ORDER BY", "LIMIT"],
            "steps": [
                {
                    "type": "explain",
                    "title": "Reihenfolge ist eine eigene Frage",
                    "text": "Ohne `ORDER BY` ist die Reihenfolge egal. Mit `ORDER BY` sagst du, wie sortiert wird.",
                    "sql": "SELECT order_number, client\nFROM orders\nORDER BY order_number DESC;",
                    "plain": "Zeige Auftragsnummer und Kunde, höchste Nummer zuerst.",
                    "parts": [
                        {"match": "SELECT order_number, client", "token": "SELECT", "question": "Was?", "answer": "Nummer und Kunde."},
                        {"match": "FROM orders", "token": "FROM", "question": "Woher?", "answer": "Aufträge."},
                        {
                            "match": "ORDER BY order_number DESC",
                            "token": "ORDER BY",
                            "question": "Sortierung?",
                            "answer": "`DESC` = absteigend (groß nach klein). `ASC` = aufsteigend (klein nach groß), das ist die Voreinstellung.",
                        },
                    ],
                    "concepts": ["ORDER BY"],
                },
                {
                    "type": "predict",
                    "title": "Wer liegt vorne?",
                    "text": "Bei `ORDER BY order_number DESC` — markiere **nur die erste Ergebniszeile** (höchste Nummer).",
                    "sql": "SELECT * FROM orders ORDER BY order_number DESC;",
                    "table": orders_table("id", "order_number", "client", "status"),
                    "expected_ids": [8],
                    "id_field": "id",
                    "single": True,
                    "execute": True,
                    "concepts": ["ORDER BY"],
                    "feedback_ok": "4718 ist die höchste Nummer — die kommt bei DESC zuerst.",
                    "feedback_bad": "DESC = die größte `order_number` zuerst. Schau nach 4718.",
                },
                {
                    "type": "explain",
                    "title": "LIMIT schneidet ab",
                    "text": "`LIMIT 5` heißt: höchstens fünf Zeilen. Zusammen mit ORDER BY bekommst du „die fünf …sten“.",
                    "sql": "SELECT *\nFROM orders\nORDER BY created_at DESC\nLIMIT 5;",
                    "plain": "Die fünf neuesten Aufträge.",
                    "parts": [
                        {
                            "match": "ORDER BY created_at DESC",
                            "token": "ORDER BY",
                            "question": "Sortierung?",
                            "answer": "Neues Datum zuerst.",
                        },
                        {
                            "match": "LIMIT 5",
                            "token": "LIMIT",
                            "question": "Wie viele?",
                            "answer": "Nur fünf Zeilen — nach dem Sortieren.",
                        },
                    ],
                    "concepts": ["LIMIT", "ORDER BY"],
                },
                {
                    "type": "build",
                    "title": "Fünf neueste",
                    "prompt": "Zeige die fünf neuesten Aufträge.",
                    "pieces": ["SELECT", "*", "FROM", "orders", "ORDER", "BY", "created_at", "DESC", "LIMIT", "5"],
                    "distractors": ["ASC", "10"],
                    "solution": "SELECT * FROM orders ORDER BY created_at DESC LIMIT 5;",
                    "ordered": True,
                    "expect_limit": True,
                    "concepts": ["ORDER BY", "LIMIT"],
                    "hints": [
                        "Neueste zuerst sortieren, dann auf 5 begrenzen.",
                        "ORDER BY created_at DESC LIMIT 5",
                    ],
                },
                {
                    "type": "apply",
                    "title": "Die Praxisfrage",
                    "prompt": "Zeige nur Auftragsnummer und Status der fünf neuesten Aufträge.",
                    "placeholder": "SELECT …",
                    "solution": "SELECT order_number, status FROM orders ORDER BY created_at DESC LIMIT 5;",
                    "strict_columns": True,
                    "ordered": True,
                    "expect_limit": True,
                    "concepts": ["SELECT", "ORDER BY", "LIMIT"],
                    "hints": [
                        "SELECT wählt die Spalten, ORDER BY die Reihenfolge, LIMIT die Anzahl.",
                        "SELECT order_number, status FROM orders ORDER BY created_at DESC LIMIT 5;",
                    ],
                },
            ],
        },
        {
            "id": "challenge-1",
            "chapter": 7,
            "title": "Challenge: Offene Red-Bull-Aufträge",
            "minutes": 6,
            "goal": "Du übersetzt eine Lagerfrage in SQL — ohne dass die App die Befehle nennt.",
            "concepts": ["SELECT", "WHERE", "AND", "ORDER BY"],
            "challenge": True,
            "model": ["SELECT", "FROM", "WHERE", "ORDER BY"],
            "steps": [
                {
                    "type": "look",
                    "title": "Keine Syntax-Liste",
                    "text": "Das Lager will etwas wissen. Du entscheidest selbst, **welche Spalten**, **welche Zeilen** und **welche Reihenfolge** du brauchst.\n\nDie Tabelle kennst du.",
                    "table": orders_table("order_number", "client", "status", "created_at"),
                    "cta": "Aufgabe öffnen",
                },
                {
                    "type": "challenge",
                    "title": "Lagerfrage",
                    "prompt": "Das Lager möchte wissen: Welche offenen Aufträge gehören aktuell zu Red Bull? Zeige nur Auftragsnummer und Status, die neuesten zuerst.",
                    "placeholder": "Übersetze die Frage in SQL…",
                    "solution": "SELECT order_number, status FROM orders WHERE client = 'Red Bull' AND status = 'open' ORDER BY created_at DESC;",
                    "strict_columns": True,
                    "ordered": True,
                    "concepts": ["SELECT", "WHERE", "AND", "ORDER BY"],
                    "hints": [
                        "Welche Zeilen? (Kunde und Status.) Welche Spalten? Wie sortieren?",
                        "Zwei Bedingungen gehören mit AND zusammen. Sortierung über created_at.",
                        "SELECT order_number, status FROM orders WHERE client = 'Red Bull' AND status = 'open' ORDER BY created_at DESC;",
                    ],
                },
                {
                    "type": "mcq",
                    "title": "Was hast du gerade getan?",
                    "question": "Welcher Denkschritt war der entscheidende — nicht die genaue Schreibweise?",
                    "options": [
                        {
                            "text": "Fachfrage zerlegen: welche Daten, welcher Filter, welche Reihenfolge.",
                            "correct": True,
                        },
                        {"text": "Die Musterlösung auswendig lernen.", "correct": False},
                        {"text": "Möglichst viele Tabellen joinen.", "correct": False},
                    ],
                    "concepts": ["SELECT", "WHERE"],
                    "explain": "SQL-Wörter sind Werkzeug. Zuerst die Frage verstehen: Was? Welche? In welcher Ordnung?",
                },
            ],
        },
    ],
}


def lessons():
    return ACADEMY["lessons"]


def lesson_by_id(lesson_id: str):
    for lesson in ACADEMY["lessons"]:
        if lesson["id"] == lesson_id:
            return lesson
    return None
